import { useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Check, Clock3, Sparkles } from "lucide-react";
import SectionHeading from "../public/SectionHeading.jsx";
import { formatUgx, resolvePublicMedia } from "../../lib/publicMedia.js";

export default function ServiceMenu({ services = [] }) {
  const categories = useMemo(() => ["All", ...new Set(services.map((service) => service.category).filter(Boolean))], [services]);
  const [activeCategory, setActiveCategory] = useState("All");
  const items = activeCategory === "All" ? services : services.filter((service) => service.category === activeCategory);
  return <section className="salon-section"><div className="salon-container"><SectionHeading eyebrow="Complete menu" title="Professional care, explained clearly." description="Browse by category and review what each service is for, what it includes and the time to allow." /><div className="mt-8 flex gap-2 overflow-x-auto pb-3">{categories.map((category) => <button key={category} type="button" onClick={() => setActiveCategory(category)} className={`shrink-0 rounded-full px-5 py-2.5 text-sm font-semibold transition ${activeCategory === category ? "bg-[var(--salon-ink)] text-white" : "border border-stone-300 bg-white hover:border-[var(--salon-copper)]"}`}>{category}</button>)}</div><div className="mt-9 grid gap-6 lg:grid-cols-2">{items.map((service, index) => <motion.article key={service.id || service.service_name} layout initial={{ opacity: 0, y: 25 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ delay: (index % 2) * .07 }} className="grid overflow-hidden rounded-[2rem] border border-stone-200 bg-white shadow-sm sm:grid-cols-[.85fr_1.15fr]"><img src={resolvePublicMedia(service.image_url, "/images/salon tools.jpg")} alt={service.service_name} className="h-full min-h-64 w-full object-cover" /><div className="p-6 sm:p-7"><p className="salon-eyebrow text-[var(--salon-copper)]"><Sparkles size={13} /> {service.category || "Professional care"}</p><h2 className="mt-3 font-serif text-2xl font-semibold">{service.service_name}</h2><p className="mt-3 text-sm leading-7 text-slate-600">{service.description}</p><p className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-slate-500">Best for</p><p className="mt-1 text-sm font-semibold">{service.idealFor || "Personalised salon care"}</p><ul className="mt-4 space-y-2">{(service.includes || []).map((item) => <li key={item} className="flex gap-2 text-sm text-slate-600"><Check size={16} className="mt-0.5 shrink-0 text-[var(--salon-copper)]" /> {item}</li>)}</ul><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-stone-200 pt-5"><strong>{service.service_amount ? formatUgx(service.service_amount) : "Price confirmed at consultation"}</strong><span className="flex items-center gap-1.5 text-xs text-slate-500"><Clock3 size={14} /> {service.duration || "Time varies"}</span></div></div></motion.article>)}</div></div></section>;
}
