import { motion } from "framer-motion";
import { leadership, teamProfessionals } from "../../content/publicContent.js";
import SectionHeading from "./SectionHeading.jsx";

function LeadershipProfile({ person, reverse }) {
  return <motion.article initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} className="grid overflow-hidden rounded-[2.25rem] border border-stone-200 bg-white shadow-sm lg:grid-cols-2 lg:items-stretch"><div className={reverse ? "lg:order-2" : ""}><img src={person.image} alt={`${person.name}, ${person.role}`} className="h-full min-h-[380px] w-full object-cover lg:min-h-[500px]" /></div><div className={`flex flex-col justify-center p-7 sm:p-10 lg:p-14 ${reverse ? "lg:order-1" : ""}`}><p className="salon-eyebrow text-[var(--salon-copper)]">Leadership</p><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-slate-500">{person.role}</p><h3 className="mt-3 font-serif text-4xl font-semibold sm:text-5xl">{person.name}</h3><p className="mt-6 text-base leading-8 text-slate-600">{person.bio}</p><p className="mt-5 text-sm leading-7 text-slate-500">This profile is prepared for the salon's real name, portrait, personal story, professional background and message to guests.</p></div></motion.article>;
}

export default function TeamShowcase({ compact = false }) {
  return <section className="salon-section"><div className="salon-container"><SectionHeading eyebrow="The people behind Salehish" title="Leadership deserves room for its own story." description="The founder and manager lead the introduction. The wider professional team follows separately." /><div className="mt-12 space-y-8">{leadership.map((person, index) => <LeadershipProfile key={person.id} person={person} reverse={index % 2 === 1} />)}</div><div className="mt-16"><div className="max-w-2xl"><p className="salon-eyebrow text-[var(--salon-copper)]">Our professionals</p><h3 className="mt-4 font-serif text-3xl font-semibold sm:text-4xl">The team delivering the everyday experience.</h3></div><div className={`mt-9 grid gap-6 ${compact ? "sm:grid-cols-2" : "sm:grid-cols-2 lg:grid-cols-3"}`}>{teamProfessionals.map((person, index) => <motion.article key={person.id} initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: index * .08 }} className="overflow-hidden rounded-[2rem] border border-stone-200 bg-white shadow-sm"><img src={person.image} alt={`${person.name}, ${person.role}`} className="aspect-[4/3] w-full object-cover" /><div className="p-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--salon-copper)]">{person.role}</p><h4 className="mt-2 font-serif text-2xl font-semibold">{person.name}</h4><p className="mt-3 text-sm leading-7 text-slate-600">{person.bio}</p></div></motion.article>)}</div></div></div></section>;
}
