import { ArrowUpRight, CirclePlay } from "lucide-react";
import { Link } from "react-router-dom";
import { galleryMedia } from "../../content/publicContent.js";
import SectionHeading from "../public/SectionHeading.jsx";

export default function SalonLifePreview() {
  const items = galleryMedia.slice(0, 4);
  return <section className="salon-section"><div className="salon-container"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><SectionHeading eyebrow="Life at Salehish" title="The work, people and energy behind every visit." description="A growing visual journal of transformations, everyday service, team moments and salon events." /><Link to="/gallery" className="salon-button-primary shrink-0">Open full gallery <ArrowUpRight size={17} /></Link></div><div className="mt-12 grid auto-rows-[250px] gap-4 md:grid-cols-4">{items.map((item, index) => <figure key={item.id} data-aos="zoom-in" data-aos-delay={index * 70} className={`group relative overflow-hidden rounded-[1.75rem] ${index === 0 ? "md:col-span-2 md:row-span-2" : index === 3 ? "md:col-span-2" : ""}`}><img src={item.poster} alt={item.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/5 to-transparent" />{item.type === "video" && <span className="absolute inset-0 grid place-items-center"><span className="grid h-14 w-14 place-items-center rounded-full bg-white/90 text-[var(--salon-ink)]"><CirclePlay size={24} /></span></span>}<figcaption className="absolute bottom-5 left-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-amber-300">{item.category}</p><p className="mt-1 font-serif text-xl font-semibold text-white">{item.title}</p></figcaption></figure>)}</div></div></section>;
}
